name: Lint Code

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # ---- JAVA ----
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
            distribution: temurin
            java-version: 21
        
      - name: Download Checkstyle
        run: curl -L -o checkstyle.jar https://github.com/checkstyle/checkstyle/releases/download/checkstyle-10.26.1/checkstyle-10.26.1-all.jar

      - name: Run Checkstyle
        run: |
            java -jar checkstyle.jar -c /google_checks.xml src/

      # ---- PYTHON ----
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python linter
        run: pip install flake8

      - name: Run Python linter
        run: flake8 .

      # ---- LUA ----
      - name: Install Lua linter
        run: |
          sudo apt-get update
          sudo apt-get install -y luarocks
          luarocks install luacheck

      - name: Run Lua linter
        run: luacheck .